#spring
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 1000MB
#数据库配置
datasource:
  # 使用druid数据源
  type: com.alibaba.druid.pool.DruidDataSource
  # 初始化时建立物理连接的个数。初始化发生在显示调用init方法，或者第一次getConnection时
  initialSize: 5
  # 最小连接数
  minIdle: 5
  # 最大连接数
  maxActive: 100
  # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，
  # 缺省启用公平锁，并发效率会有所下降，
  # 如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
  maxWait: 60000
  # 1) Destroy线程会检测连接的间隔时间
  # 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
  timeBetweenEvictionRunsMillis: 60000
  # Destory线程中如果检测到当前连接的最后活跃时间和当前时间的差值大于
  # minEvictableIdleTimeMillis，则关闭当前连接。
  minEvictableIdleTimeMillis: 30000
  # 用来检测连接是否有效的sql，要求是一个查询语句。
  # 如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
  validationQuery: select 'x'
  # 建议配置为true，不影响性能，并且保证安全性。
  # 申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis，
  # 执行validationQuery检测连接是否有效。
  testWhileIdle: true
  # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
  testOnBorrow: false
  # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
  testOnReturn: false
  # 是否缓存preparedStatement，也就是PSCache。
  # PSCache对支持游标的数据库性能提升巨大，比如说oracle。
  # 在mysql5.5以下的版本中没有PSCache功能，建议关闭掉。
  # 5.5及以上版本有PSCache，建议开启。
  poolPreparedStatements: true
  # 要启用PSCache，必须配置大于0，当大于0时，
  # poolPreparedStatements自动触发修改为true。
  # 在Druid中，不会存在Oracle下PSCache占用内存过多的问题，
  # 可以把这个数值配置大一些，比如说100
  maxPoolPreparedStatementPerConnectionSize: 100
  # 配置监控统计拦截的filters，监控统计用的stat、日志用的log4j、 防御sql注入的wall、ConfigFilter非对称加密password
  filters: stat,wall,slf4j,config
  # 打开mergeSql功能；慢SQL记录
  # ConfigFilter非对称加密的公钥，config.decrypt=true;config.decrypt.key=${publickey}
  connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIB8+939ON8hRUt98tCof3dpYVXOFd6CmTF+PRJAo3xNmlVmXbiPVcVfbqqI84PjKN6IGsCH1GfMeAAu9I5A+zsCAwEAAQ==
  #配置了两个数据源
  master:
    datasource:
      url: jdbc:mysql://120.77.32.19:3306/cess?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: cw6mq/MZWZdqXtDLzkfuNu1/GnEYrlHh6KZCXaygORuydbaM2hK7OFhldwcrljfGN1pMJ94EaCBogUucYEgWcw==
      driverClassName: com.mysql.cj.jdbc.Driver
  cluster:
    datasource:
      url: jdbc:mysql://120.77.32.19:3306/cess?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
      username: root
      password: cw6mq/MZWZdqXtDLzkfuNu1/GnEYrlHh6KZCXaygORuydbaM2hK7OFhldwcrljfGN1pMJ94EaCBogUucYEgWcw==
      driverClassName: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logback:
  logDir: log/dev

logging:
  level:
    cn.edu.cess: debug

snowflake:
  workId: 1
  datacenterId: 1