server:
  port: 8443
  servlet:
    context-path: /cess

spring:
  application:
    name: college employment service system
  profiles:
    active: dev

#雪花算法机房ID，机器ID
snowflake:
  workId: 1
  datacenterId: 1

logback:
  appName: cess
  fileType: log
