server:
  port: 8443
  servlet:
    context-path: /cess
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 1000MB
  #链接建立超时时间ms
  connection-timeout: 10000
  tomcat:
    uri-encoding: UTF-8
    #最小线程数
    min-spare-threads: 100
    #最大线程数（建议这个配置数可以在服务器CUP核心数的200~250倍之间）
    max-threads: 500
    #最大等待队列长度
    accept-count: 100
    #最大链接数
    max-connections: 600
    #请求头最大长度kb
    max-http-header-size: 1048576
    #请请求体最大长度kb
    #max-http-post-size: 2097152
    #tomcat目录
    basedir: cess-tomcat
    #tomcat日志配置
    accesslog:
      buffered: true
      directory: logs
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: '%t %a "%r" %s (%D ms)'
      prefix: access_log

spring:
  application:
    name: college employment service system
  profiles:
    active: dev
  http:
    multipart:
      enabled: true
      file-size-threshold: 50
      max-file-size: 300MB
      max-request-size: 300MB
  rabbitmq:
    host: cess-localhost
    port: 5672
    username: gnosed
    password: gnosed
    #虚拟host 可以不设置,使用server默认host
    virtual-host: gnosed
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      concurrency: 30
      max-concurrency: 60
      retry:
        enabled: true
        max-attempts: 3
  #注册到admin服务端
  boot:
    admin:
      client:
        url: http://localhost:8886/admin
#打开actuator监控
management:
  #监控端口
  server:
    port: 8887
  endpoints:
    web:
      #定制跟路径
      base-path: /actuator
      #开放所有节点，默认只开启了health info节点，也可以设置部分启动, 如：env,beans。默认是health, info
      exposure:
        include: "*"
  endpoint:
    health:
      #显示具体信息
      show-details: always

#雪花算法机房ID，机器ID
snowflake:
  workId: 1
  datacenterId: 1

xxl:
  mapper-locations: classpath*:mapper/xxljob/*.xml
  job:
    accessToken: ''
    admin:
      addresses: http://cess-localhost:19880/xxl-job-admin-1.9.1
    executor:
      appname: cess-executor
      ip: ''
      logpath: /home/baby/tools/xxljob_19880/executor-log
      logretentiondays: -1
      port: 9999
  jobinfo:
    delete:
      url: http://cess-localhost:19880/xxl-job-admin-1.9.1/jobinfo/remove
    add:
      url: http://cess-localhost:19880/xxl-job-admin-1.9.1/jobinfo/add
    update:
      url: http://cess-localhost:19880/xxl-job-admin-1.9.1/jobinfo/update
    pause:
      url: http://cess-localhost:19880/xxl-job-admin-1.9.1/jobinfo/pause

seckill:
  url: http://cess-localhost:8446

elasticsearch:
  hostandport: cess-localhost:9200
  #职位搜索是否开启es,true or false
  positions:
    search: false
