package cn.edu.cess.mapper.xxljob;


import cn.edu.cess.entity.xxljob.XxlJobInfo;
import cn.edu.cess.mapper.base.AbstractDao;
import cn.edu.cess.mapper.base.BaseDao;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public class XxlJobDao extends BaseDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sec_staff
     *
     * @mbggenerated
     */
    private final String MAPPER_NAMESPACE = "XxlJobMapper.";


    /**
     * 插入数据
     *
     * @param bean
     * @return
     */
    public int insertXxlJobTrigger(XxlJobInfo bean) {
        int result = update(MAPPER_NAMESPACE.concat("insertXxlJobTrigger"), bean);
        return result;
    }

    public List<XxlJobInfo> triggerList(String handler) {
        return getList(MAPPER_NAMESPACE.concat("triggerList"), handler);
    }

    public List<XxlJobInfo> triggerListByModel(XxlJobInfo xxlJobInfo) {
        return getList(MAPPER_NAMESPACE.concat("triggerListByModel"), xxlJobInfo);
    }


}
